### ISSUE TITLE
Develop Algorithm for Learning Flashcards

### ISSUE THREAD

**Issue by jacob-macleod** [jacob-macleod/Flashcard-App#27]
The algorithm should be similar to Anki, and allow users to be shown only the flashcards they need to learn
The client should pass an API endpoint the card data like review date and review status, and the new review date and status should be returned.

In Anki, cards are classed as Learn, hard, medium, easy. Easy is rarely used, and I would argue "hard" is used even less. So I would say:
- If you swipe the card one way, you don't know it
- If you swipe the card the other way, you know it
- If you tap the card to flip it then press the "Easy" button or equivalent, the flashcard is classed as easy

**Comment by jacob-macleod** [comment]
@nathan-a-macleod This is pertinent to you for the UI design

**Comment by nathan-a-macleod** [comment]
Pertinent? That's a big word for you... Sure you know what it means?

**Comment by jacob-macleod** [comment]
I know way bigger words. Like database-view-renderer-engine. That's a pretty big word.

**Comment by jacob-macleod** [comment]
This has now been completed
