### ISSUE TITLE
KeyError on create-account endpoint (local database config)

### ISSUE THREAD

**Issue by jaymeklein** [jacob-macleod/Flashcard-App#88]
I was testing the `create-account` endpoint via [/api/create-account](http://127.0.0.1:5000/api/create-account) with the following parameters:

```
{
    "userID": "1231",
    "displayName": "Jayme Klein"
}
```

`database_config.py` is configured as  `type="local"` 

I had this exception when trying to create a new user:

```
Flashcard-App\backend\database\local_database.py", line 41, in _traverse_path
    current = current[key]
              ^^^^^^^^^^^^
KeyError: ''
```
and these were the values the method was using:
![image](https://github.com/jacob-macleod/Flashcard-App/assets/18254213/10225569-90cb-4739-95f5-d2e5a3c994f9)

Event with an existing user in the file, the `''` key would not be found:
![image](https://github.com/jacob-macleod/Flashcard-App/assets/18254213/05de3c85-05d6-4bfe-ad66-477bbda29261)

Should an empty `''` key exist in `data.json` file?

I'm gonna skip this endpoint for the moment.

Please let me know if you need more context or if the issue is not properly writen.

**Comment by jacob-macleod** [comment]
I've fixed this now, so if you merge from main the changes should be applied. The bug was because for a local database, there was no check done to make sure the keys looked for actually exist.

**Comment by jaymeklein** [comment]
Perfect, thanks for fixing this issue.
I'm gonna keep on my tests branch then, and report any new problems i have with the API.
